export const mockMedicines = [
  {
    id: 'amlodipine',
    name: '암로디핀',
    ingredientName: 'Amlodipine',
    ingredientCode: 'ING-AML-001',
    category: '혈압약',
    company: '세이프제약',
    description: '고혈압과 협심증 치료에 사용되는 칼슘채널차단제입니다.',
  },
  {
    id: 'metformin',
    name: '메트포르민',
    ingredientName: 'Metformin',
    ingredientCode: 'ING-MET-002',
    category: '당뇨약',
    company: '건강팜',
    description: '제2형 당뇨병에서 혈당 조절을 돕는 약입니다.',
  },
  {
    id: 'cimetidine',
    name: '시메티딘',
    ingredientName: 'Cimetidine',
    ingredientCode: 'ING-CIM-003',
    category: '위장약',
    company: '메디케어',
    description: '위산 분비를 줄이는 H2 수용체 길항제입니다.',
  },
  {
    id: 'ibuprofen',
    name: '이부프로펜',
    ingredientName: 'Ibuprofen',
    ingredientCode: 'ING-IBU-004',
    category: '소염진통제',
    company: '바른약품',
    description: '통증과 염증을 줄이는 비스테로이드성 소염진통제입니다.',
  },
  {
    id: 'acetaminophen',
    name: '아세트아미노펜',
    ingredientName: 'Acetaminophen',
    ingredientCode: 'ING-ACE-005',
    category: '해열진통제',
    company: '해피헬스',
    description: '발열과 통증 완화에 사용되는 해열진통제입니다.',
  },
  {
    id: 'codeine',
    name: '코데인',
    ingredientName: 'Codeine',
    ingredientCode: 'ING-COD-006',
    category: '진해진통제',
    company: '케어랩',
    description: '기침 억제와 통증 완화에 사용되는 성분입니다.',
  },
  {
    id: 'warfarin',
    name: '와파린',
    ingredientName: 'Warfarin',
    ingredientCode: 'ING-WAR-007',
    category: '항응고제',
    company: '라이프메드',
    description: '혈전 생성을 줄이기 위해 사용하는 항응고제입니다.',
  },
  {
    id: 'aspirin',
    name: '아스피린',
    ingredientName: 'Aspirin',
    ingredientCode: 'ING-ASP-008',
    category: '항혈소판제',
    company: '온누리제약',
    description: '통증 완화와 혈소판 응집 억제에 사용되는 약입니다.',
  },
  {
    id: 'rosuvastatin',
    name: '로수바스타틴',
    ingredientName: 'Rosuvastatin',
    ingredientCode: 'ING-ROS-009',
    category: '고지혈증약',
    company: '청솔제약',
    description: '콜레스테롤 수치를 낮추는 스타틴 계열 약입니다.',
  },
  {
    id: 'omeprazole',
    name: '오메프라졸',
    ingredientName: 'Omeprazole',
    ingredientCode: 'ING-OME-010',
    category: '위장약',
    company: '케이메디',
    description: '위산 분비를 억제하는 프로톤펌프억제제입니다.',
  },
];

export const pairRules = [
  {
    medicineIds: ['cimetidine', 'metformin'],
    severity: 'danger',
    reason: '메트포르민 혈중 농도 상승 위험이 있어 주의가 필요합니다.',
    source: 'DUR 병용금기 데이터',
  },
  {
    medicineIds: ['warfarin', 'aspirin'],
    severity: 'danger',
    reason: '출혈 위험이 증가할 수 있습니다.',
    source: 'DUR 병용주의 데이터',
  },
  {
    medicineIds: ['ibuprofen', 'aspirin'],
    severity: 'warning',
    reason: '위장관 출혈 위험이 증가할 수 있습니다.',
    source: '노인주의 및 상호작용 데이터',
  },
];

export const nsaidIds = new Set(['ibuprofen', 'aspirin']);
export const pregnantCautionIds = new Set(['codeine']);
